### ISSUE TITLE
Failed to resolve: com.github.bumptech.glide:glide:4.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by farmazon3000** [florent37/GlidePalette#19]
I've added dependency
`
compile 'com.github.florent37:glidepalette:2.0.0'
`
and I'm getting:
`
Error:Failed to resolve: com.github.bumptech.glide:glide:4.0.0-SNAPSHOT
<a href="openFile:/home/githubzz/App/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
`

**Comment by Danihelsan** [comment]
same here...will need to avoid using the library atm

**Comment by florent37** [comment]
please try with 

``` java
maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
```

**Comment by IsaacCleverCode** [comment]
I tried it with the following and I still got "Failed to resolve..."

 maven {
            name 'glide-snapshot'
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }

My dependencies are as follows: 

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.android.support:leanback-v17:24.1.1'
    compile 'com.github.bumptech.glide:glide:4.0.0-SNAPSHOT'
    compile 'com.github.bumptech.glide:okhttp-integration:2.0.0-SNAPSHOT'
    compile 'com.android.support:support-v4:24.0.0'
}

**Comment by techscientist** [comment]
Any updates, @florent37 ?

**Comment by zhenalexfan** [comment]
Same problem.

**Comment by fishsnacks** [comment]
Same issue

Fixed in build.gradle (parent) by adding requirement after reading the documentation more carefully...
  maven {
    name 'glide-snapshot'
    url 'http://oss.sonatype.org/content/repositories/snapshots'
  }

**Comment by dulimarta** [comment]
I fixed the 4.0.0-SNAPSHOT error by placing the `maven` section under `allprojects.repositories`.

```
allprojects {
    repositories {
        jcenter()
        maven {
            name 'glide-snapshot'
            url 'http://oss.sonatype.org/content/repositories/snapshots'
        }
    }
}
```

**Comment by florent37** [comment]
v2.1.0

**Comment by mahdi-malv** [comment]
In case 
```
compile 'com.github.bumptech.glide:glide:4.0.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'
```
Add `mavenCentral()` to 
```
allprojects {
    repositories {
        jcenter()
    }
}
```
