### ISSUE TITLE
Glide 4.0.0-SNAPSHOT not accepting center crop?

### ISSUE THREAD

**Issue by zhenalexfan** [florent37/GlidePalette#22]
For GlidePalette I use Glide 4.0.0-SNAPSHOT instead of 3.7.0. 
But I'm no longer able to use `centerCrop()` and `crossfade()` now.

**Comment by wezley98** [comment]
Have you tried the newest version
http://bumptech.github.io/glide/doc/download-setup.html

**Comment by florent37** [comment]
v2.1.0
