### ISSUE TITLE
Failed to resolve: com.github.bumptech.glide:glide:4.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by DanteAndroid** [florent37/GlidePalette#24]
Error:(75, 13) Failed to resolve: com.github.bumptech.glide:glide:4.0.0-SNAPSHOT
<a href="openFile:/Volumes/Projects/APractice/TimeDiary/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Nileshwari** [comment]
Please add 
 maven {
            name 'glide-snapshot'
            url 'http://oss.sonatype.org/content/repositories/snapshots'
        }

in your application gradle file

**Comment by wezley98** [comment]
There is a newer version which does not require that repo

http://bumptech.github.io/glide/doc/download-setup.html

**Comment by florent37** [comment]
v2.1.0
