### ISSUE TITLE
Android support library error (Update the glide palette sdk)

### ISSUE THREAD

**Issue by Shreyas-R** [florent37/GlidePalette#25]
After updating  Android Studio and the SDKs, I'm getting error in build.gradle dependencies saying that android support library mismatch. All the SDKs have been updated while Glide palette still uses old SDKs (mixing versions can lead to runtime crashes). Please update the glide palette sdk with latest support library.

My android-support SDK is at: 26.0.0-alpha1

**Comment by krimuru** [comment]
what is the solution now? even i have the same problem.

**Comment by florent37** [comment]
working on this :) and glide version
