### ISSUE TITLE
Update SDK to Android O: v26.0.0

### ISSUE THREAD

**Issue by Shreyas-R** [florent37/GlidePalette#27]
After updating Android Studio and the SDKs, I'm getting error in build.gradle dependencies saying that android support library mismatch. All the SDKs have been updated while Glide palette still uses old SDKs (mixing versions can lead to runtime crashes). Please update the glide palette sdk with latest support library.

My android-support SDK is at: 26.0.0-alpha1

**Comment by florent37** [comment]
As an open source library I can't force user to use an alpha dependency :/

But you can exclude the one present in my library

**Comment by Shreyas-R** [comment]
Yes I can understand that but google has already released stable version which I have updated to now. Now you can update I think.

Now my android-support SDK is at: 26.0.0

Also, what do you mean by "you can exclude the one present in my library" ?

**Comment by florent37** [comment]
compile ("....") {
     exclude group: 'com.android.support', 'module': 'support-v7'
}

**Comment by sevar83** [comment]
This works for me on 26.0.1:
```
compile "com.android.support:palette-v7:$supportLibVersion"
compile ("....") {
  exclude group: 'com.android.support', 'module': 'palette-v7'
}
```

**Comment by florent37** [comment]
done, you can try the `2.1.2`
